import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navigation from "@/components/navigation";
import AppNavigation from "@/components/appNavigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="flex flex-col p-4 pt-2 max-h-screen overflow-hidden items-center">
      <div className="flex w-full max-h-screen max-w-[1024px] gap-4">
        <Navigation />
        <AppNavigation />
        {children}
      </div>
    </main>
  );
}
